import "@fontsource-variable/newsreader";
import "@fontsource-variable/source-sans-3";
import "./styles.css";

const MONEY=[1,5,10,25,50,75,100,200,300,400,500,750,1000,2500,5000,7500,10000,20000,30000,40000,50000,75000,100000,250000,500000,1000000];
const HENYO_WORDS=["Adobo","Jeepney","Karaoke","Tsinelas","Halo-halo","Manny Pacquiao","Jollibee","Payong","Sinigang","Basketball","Palengke","Tricycle"];
const app=document.querySelector("#app");
const peso=n=>`₱${n.toLocaleString("en-PH")}`;
const focus=q=>requestAnimationFrame(()=>document.querySelector(q)?.focus());
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const parseValues=text=>text.split(/[\n,;]+/).map(x=>Number(x.replace(/[₱\s]/g,""))).filter(n=>Number.isFinite(n)&&n>=0);
const parseWords=text=>text.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);
let timerId=null;
let state={phase:"menu",dealValues:MONEY,henyoWords:HENYO_WORDS,score:0};

function stopTimer(){if(timerId){clearInterval(timerId);timerId=null}}
function menu(){stopTimer();state={...state,phase:"menu"};render();focus('[data-game="deal"]')}

// Deal or No Deal
const unopened=()=>state.cases.filter(c=>!c.opened&&c.number!==state.mine);
const remaining=()=>state.cases.filter(c=>!c.opened).map(c=>c.value);
function target(){const left=unopened().length;if(left<=4)return 1;if(left<=Math.ceil(state.cases.length*.45))return Math.min(2,left);return Math.min(3,left)}
function bankerOffer(){const a=remaining(),mean=a.reduce((x,y)=>x+y,0)/a.length,progress=1-a.length/state.cases.length,factor=.35+progress*.55,step=mean>=1000?100:1;return Math.max(step,Math.round(mean*factor/step)*step)}
function dealSetup(){stopTimer();const values=state.dealValues?.length?state.dealValues:MONEY;state={...state,phase:"deal-setup",error:"",caseCount:values.length,dealValues:values};render();focus("#case-count")}
function submitDealSetup(e){e.preventDefault();const data=new FormData(e.currentTarget),count=Number(data.get("caseCount")),values=parseValues(String(data.get("values")||""));if(!Number.isInteger(count)||count<2||count>40)state.error="Enter a case count from 2 to 40.";else if(values.length!==count)state.error=`You entered ${values.length} valid values. Enter exactly ${count}.`;else{startDeal(count,values);return}state.caseCount=count||26;state.dealValues=values;render();focus("#case-count")}
function startDeal(count,values){state={...state,phase:"deal-choose",cases:shuffle(values).map((value,i)=>({number:i+1,value,opened:false})),mine:null,round:0,opened:0,offer:null,result:null,message:"Pumili ng sarili mong briefcase. Ito ang itatabi mo hanggang dulo.",caseCount:count,dealValues:values};render()}
function chooseCase(n){state.mine=n;state.phase="deal-opening";state.roundTarget=target();state.message=`Briefcase #${n} ang iyong case. Magbukas ng ${state.roundTarget} cases.`;render();focus(".case:not(:disabled)")}
function openCase(n){if(state.phase!=="deal-opening"||n===state.mine)return;const c=state.cases.find(x=>x.number===n);if(!c||c.opened)return;c.opened=true;state.opened++;const left=state.roundTarget-state.opened;state.message=`Briefcase #${n}: ${peso(c.value)}. ${Math.max(0,left)} pa sa round na ito.`;if(left<=0||!unopened().length){state.offer=bankerOffer();state.phase="deal-offer";state.message="Tumatawag ang banker… Deal or No Deal?"}render();focus(state.phase==="deal-offer"?'[data-action="deal"]':".case:not(:disabled)")}
function acceptDeal(){state.phase="deal-finished";state.result=state.offer;state.message=`Deal! Ang napanalunan mo ay ${peso(state.result)}.`;render();focus('[data-action="deal-restart"]')}
function rejectDeal(){if(!unopened().length){const own=state.cases.find(c=>c.number===state.mine);state.phase="deal-finished";state.result=own.value;state.message=`Ang laman ng Briefcase #${own.number} ay ${peso(own.value)}!`}else{state.round++;state.opened=0;state.phase="deal-opening";state.roundTarget=target();state.message=`No Deal! Magbukas ng ${state.roundTarget} ${state.roundTarget===1?"case":"cases"}.`}render();focus(state.phase==="deal-finished"?'[data-action="deal-restart"]':".case:not(:disabled)")}

// Pinoy Henyo
function henyoSetup(){stopTimer();state={...state,phase:"henyo-setup",henyoError:"",duration:state.duration||60};render();focus("#henyo-words")}
function submitHenyo(e){e.preventDefault();const data=new FormData(e.currentTarget),words=parseWords(String(data.get("words")||"")),duration=Number(data.get("duration"));if(!words.length){state.henyoError="Enter at least one secret word.";render();focus("#henyo-words");return}state={...state,phase:"henyo-ready",henyoWords:words,henyoQueue:shuffle(words),duration,seconds:duration,score:0,round:1};render();focus('[data-action="reveal-word"]')}
function revealWord(){state.phase="henyo-playing";state.seconds=state.duration;render();timerId=setInterval(()=>{state.seconds--;const display=document.querySelector(".timer-value");if(display)display.textContent=state.seconds;if(state.seconds<=0)finishHenyo(false,true)},1000);focus('[data-result="correct"]')}
function finishHenyo(correct,timedOut=false){if(state.phase!=="henyo-playing")return;stopTimer();if(correct)state.score++;state.lastCorrect=correct;state.timedOut=timedOut;state.phase="henyo-result";render();focus('[data-action="next-word"]')}
function nextWord(){state.henyoQueue.shift();if(!state.henyoQueue.length){state.henyoQueue=shuffle(state.henyoWords)}state.round++;state.seconds=state.duration;state.phase="henyo-ready";render();focus('[data-action="reveal-word"]')}

function shellHeader(title,action="menu"){return `<header class="hub-header"><button class="hub-home" data-action="${action}">← Game menu</button><strong>${title}</strong><span>Larong Pinoy</span></header>`}
function menuView(){return `<main class="hub" id="main"><header class="hub-hero"><div class="hub-mark">LARONG <b>PINoy</b></div><h1>Pili na.<br><em>Laro tayo.</em></h1><p>Two classic Filipino game-night favorites, ready for the whole barkada.</p></header><section class="game-menu" aria-label="Choose a game"><button class="game-choice deal-choice" data-game="deal"><small>Luck · Strategy · Suspense</small><strong>Deal or<br>No Deal</strong><span>Customize the cases and money board, then face the banker. <b>Play →</b></span></button><button class="game-choice henyo-choice" data-game="henyo"><small>Guessing · Teamwork · Bilisan</small><strong>Pinoy<br>Henyo</strong><span>Load your secret words, start the clock, and ask away. <b>Play →</b></span></button></section></main>`}
function dealSetupView(){const values=(state.dealValues?.length?state.dealValues:MONEY).join("\n");return `${shellHeader("Deal or No Deal")}<main class="setup-page" id="main"><section class="setup-intro"><div class="show-logo"><strong>DEAL</strong><i>OR</i><strong>NO DEAL</strong></div><h1>Build tonight’s<br><em>money board.</em></h1><p>Choose how many briefcases will be used, then enter one peso value for every case.</p></section><section class="setup-panel"><div><h2>Game setup</h2><p>Values may be separated by commas or entered one per line.</p></div><form id="deal-setup-form" novalidate><label for="case-count">Number of briefcases <small>2–40 cases</small></label><input id="case-count" name="caseCount" type="number" min="2" max="40" value="${state.caseCount||26}" required><label for="game-values">Peso values <small>One value per case</small></label><textarea id="game-values" name="values" rows="12" required>${values}</textarea><p class="setup-status ${state.error?"is-error":""}" aria-live="polite">${state.error||`${state.dealValues?.length||MONEY.length} values ready.`}</p><button class="primary setup-start">Start the game</button></form></section></main>`}
function caseView(c){const mine=c.number===state.mine,active=state.phase==="deal-choose"||(state.phase==="deal-opening"&&!mine),label=c.opened?peso(c.value):mine?`#${c.number} · YOURS`:`#${c.number}`;return `<button class="case ${c.opened?"is-open":""} ${mine?"is-mine":""}" data-case="${c.number}" ${!active||c.opened?"disabled":""} aria-label="${c.opened?`Briefcase ${c.number}, opened, ${peso(c.value)}`:mine?`Your briefcase, number ${c.number}`:`Briefcase ${c.number}`}"><i aria-hidden="true"></i><span>${label}</span></button>`}
function board(){const opened=new Map(),seen=new Map();state.cases.filter(c=>c.opened).forEach(c=>opened.set(c.value,(opened.get(c.value)||0)+1));return [...state.dealValues].sort((a,b)=>a-b).map(v=>{const occurrence=(seen.get(v)||0)+1;seen.set(v,occurrence);return `<li class="${occurrence<=(opened.get(v)||0)?"eliminated":""}">${peso(v)}</li>`}).join("")}
function dealControls(){if(state.phase==="deal-offer")return `<section class="offer"><p>Banker’s offer</p><h2>${peso(state.offer)}</h2><div><button class="primary" data-action="deal">Deal</button><button class="secondary" data-action="nodeal">No Deal</button></div></section>`;if(state.phase==="deal-finished"){const own=state.cases.find(c=>c.number===state.mine);return `<section class="offer"><p>Your result</p><h2>${peso(state.result)}</h2><small>Your Briefcase #${own.number} held ${peso(own.value)}.</small><button class="primary full" data-action="deal-restart">Play again</button></section>`}const n=state.phase==="deal-opening"?Math.max(0,state.roundTarget-state.opened):1;return `<section class="round-card"><p>${state.phase==="deal-choose"?"Choose one case to keep":`Open ${n} more ${n===1?"case":"cases"}`}</p><strong>${state.phase==="deal-choose"?"Your luck starts here.":"Every reveal changes the offer."}</strong></section>`}
function dealGameView(){const label=state.phase==="deal-choose"?"Opening move":state.phase==="deal-finished"?"Game complete":`Round ${state.round+1}`;return `${shellHeader("Deal or No Deal")}<main id="main"><div class="game-shell"><aside class="money-board"><h2>Prize board</h2><ol>${board()}</ol></aside><section class="stage"><div class="stage-heading"><p>${label}</p><h1>Deal or<br><em>No Deal?</em></h1></div><div class="cases" style="--case-columns:${Math.min(6,Math.max(2,Math.ceil(Math.sqrt(state.caseCount))))}">${state.cases.map(caseView).join("")}</div></section><aside class="control-room"><div class="host-message" aria-live="polite"><span>Host</span><p>${state.message}</p></div>${dealControls()}<button class="secondary full" data-action="deal-setup">Change game setup</button></aside></div></main>`}
function henyoSetupView(){return `${shellHeader("Pinoy Henyo")}<main class="henyo-setup" id="main"><section><h1>Ihanda ang<br><em>mga salita.</em></h1><p>One player holds the screen up. Everyone else answers only “Oo,” “Hindi,” or “Pwede.”</p></section><form id="henyo-setup-form"><label for="henyo-words">Secret words <small>One per line</small></label><textarea id="henyo-words" name="words" rows="12">${(state.henyoWords||HENYO_WORDS).join("\n")}</textarea><label for="duration">Time per word</label><select id="duration" name="duration"><option value="30">30 seconds</option><option value="60" ${state.duration!==90&&state.duration!==120?"selected":""}>60 seconds</option><option value="90" ${state.duration===90?"selected":""}>90 seconds</option><option value="120" ${state.duration===120?"selected":""}>120 seconds</option></select><p class="setup-status is-error" aria-live="polite">${state.henyoError||""}</p><button class="henyo-start">Ready na!</button></form></main>`}
function henyoView(){const word=state.henyoQueue[0];if(state.phase==="henyo-ready")return `${shellHeader("Pinoy Henyo")}<main class="henyo-ready" id="main"><p>Round ${state.round} · Score ${state.score}</p><h1>Ipasa ang device<br>sa manghuhula.</h1><span>Keep the screen hidden until it is on their forehead.</span><button data-action="reveal-word">Reveal word & start timer</button></main>`;if(state.phase==="henyo-result")return `${shellHeader("Pinoy Henyo")}<main class="henyo-result" id="main"><p>${state.timedOut?"Time’s up!":state.lastCorrect?"Tumpak!":"Pass muna"}</p><h1>${word}</h1><strong>Score: ${state.score}</strong><button data-action="next-word">Next word</button><button class="text-button" data-action="henyo-setup">End game</button></main>`;return `${shellHeader("Pinoy Henyo")}<main class="henyo-play" id="main"><div class="henyo-meta"><span>Round ${state.round}</span><strong class="timer-value" aria-live="polite">${state.seconds}</strong><span>Score ${state.score}</span></div><section class="secret-word" aria-label="Secret word"><p>Hulaan mo:</p><h1>${word}</h1></section><div class="henyo-answers" aria-label="Allowed answers"><span>OO</span><span>HINDI</span><span>PWEDE</span></div><div class="henyo-actions"><button data-result="pass">Pass</button><button data-result="correct">Tama!</button></div></main>`}

function render(){app.innerHTML=state.phase==="menu"?menuView():state.phase==="deal-setup"?dealSetupView():state.phase.startsWith("deal-")?dealGameView():state.phase==="henyo-setup"?henyoSetupView():henyoView();document.querySelectorAll('[data-action="menu"]').forEach(b=>b.onclick=menu);document.querySelector('[data-game="deal"]')?.addEventListener("click",dealSetup);document.querySelector('[data-game="henyo"]')?.addEventListener("click",henyoSetup);document.querySelector("#deal-setup-form")?.addEventListener("submit",submitDealSetup);document.querySelector("#henyo-setup-form")?.addEventListener("submit",submitHenyo);document.querySelectorAll("[data-case]").forEach(b=>b.onclick=()=>state.phase==="deal-choose"?chooseCase(+b.dataset.case):openCase(+b.dataset.case));document.querySelector('[data-action="deal"]')?.addEventListener("click",acceptDeal);document.querySelector('[data-action="nodeal"]')?.addEventListener("click",rejectDeal);document.querySelector('[data-action="deal-restart"]')?.addEventListener("click",()=>startDeal(state.caseCount,state.dealValues));document.querySelector('[data-action="deal-setup"]')?.addEventListener("click",dealSetup);document.querySelector('[data-action="henyo-setup"]')?.addEventListener("click",henyoSetup);document.querySelector('[data-action="reveal-word"]')?.addEventListener("click",revealWord);document.querySelector('[data-result="correct"]')?.addEventListener("click",()=>finishHenyo(true));document.querySelector('[data-result="pass"]')?.addEventListener("click",()=>finishHenyo(false));document.querySelector('[data-action="next-word"]')?.addEventListener("click",nextWord)}
render();
