import "@fontsource-variable/newsreader";
import "@fontsource-variable/source-sans-3";
import "./styles.css";

const DEFAULTS=[1,5,10,25,50,75,100,200,300,400,500,750,1000,2500,5000,7500,10000,20000,30000,40000,50000,75000,100000,250000,500000,1000000];
const app=document.querySelector("#app");
const peso=n=>`₱${n.toLocaleString("en-PH")}`;
const focus=q=>requestAnimationFrame(()=>document.querySelector(q)?.focus());
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const parseValues=text=>text.split(/[\n,;]+/).map(x=>Number(x.replace(/[₱\s]/g,""))).filter(n=>Number.isFinite(n)&&n>=0);
let state={phase:"setup",error:"",caseCount:26,values:DEFAULTS};

const unopened=()=>state.cases.filter(c=>!c.opened&&c.number!==state.mine);
const remaining=()=>state.cases.filter(c=>!c.opened).map(c=>c.value);
function target(){const left=unopened().length;if(left<=4)return 1;if(left<=Math.ceil(state.cases.length*.45))return Math.min(2,left);return Math.min(3,left)}
function bankerOffer(){const a=remaining(),mean=a.reduce((x,y)=>x+y,0)/a.length,progress=1-a.length/state.cases.length,factor=.35+progress*.55,step=mean>=1000?100:1;return Math.max(step,Math.round(mean*factor/step)*step)}

function start(count,values){state={phase:"choose",cases:shuffle(values).map((value,i)=>({number:i+1,value,opened:false})),mine:null,round:0,opened:0,offer:null,result:null,message:"Pumili ng sarili mong briefcase. Ito ang itatabi mo hanggang dulo.",caseCount:count,values};render()}
function setup(e){e.preventDefault();const data=new FormData(e.currentTarget),count=Number(data.get("caseCount")),values=parseValues(String(data.get("values")||""));if(!Number.isInteger(count)||count<2||count>40)state.error="Enter a case count from 2 to 40.";else if(values.length!==count)state.error=`You entered ${values.length} valid values. Enter exactly ${count}.`;else{start(count,values);return}state.caseCount=count||26;state.values=values;render();focus("#case-count")}
function showSetup(){const values=state.values?.length?state.values:DEFAULTS;state={phase:"setup",error:"",caseCount:values.length,values};render();focus("#case-count")}
function choose(n){state.mine=n;state.phase="opening";state.roundTarget=target();state.message=`Briefcase #${n} ang iyong case. Magbukas ng ${state.roundTarget} cases.`;render();focus(".case:not(:disabled)")}
function openCase(n){if(state.phase!=="opening"||n===state.mine)return;const c=state.cases.find(x=>x.number===n);if(!c||c.opened)return;c.opened=true;state.opened++;const left=state.roundTarget-state.opened;state.message=`Briefcase #${n}: ${peso(c.value)}. ${Math.max(0,left)} pa sa round na ito.`;if(left<=0||!unopened().length){state.offer=bankerOffer();state.phase="offer";state.message="Tumatawag ang banker… Deal or No Deal?"}render();focus(state.phase==="offer"?'[data-action="deal"]':".case:not(:disabled)")}
function deal(){state.phase="finished";state.result=state.offer;state.message=`Deal! Ang napanalunan mo ay ${peso(state.result)}.`;render();focus('[data-action="restart"]')}
function noDeal(){if(!unopened().length){const own=state.cases.find(c=>c.number===state.mine);state.phase="finished";state.result=own.value;state.message=`Ang laman ng Briefcase #${own.number} ay ${peso(own.value)}!`}else{state.round++;state.opened=0;state.phase="opening";state.roundTarget=target();state.message=`No Deal! Magbukas ng ${state.roundTarget} ${state.roundTarget===1?"case":"cases"}.`}render();focus(state.phase==="finished"?'[data-action="restart"]':".case:not(:disabled)")}

function setupView(){const values=(state.values?.length?state.values:DEFAULTS).join("\n");return `<main class="setup-page" id="main"><section class="setup-intro"><div class="show-logo"><span>KAPAMILYA</span><strong>DEAL</strong><i>OR</i><strong>NO DEAL</strong></div><h1>Build tonight’s<br><em>money board.</em></h1><p>Choose how many briefcases will be used, then enter one peso value for every case.</p></section><section class="setup-panel" aria-labelledby="setup-title"><div><h2 id="setup-title">Game setup</h2><p>Values may be separated by commas or entered one per line.</p></div><form id="setup-form" novalidate><label for="case-count">Number of briefcases <small>2–40 cases</small></label><input id="case-count" name="caseCount" type="number" min="2" max="40" value="${state.caseCount||26}" required><label for="game-values">Peso values <small>One value per case</small></label><textarea id="game-values" name="values" rows="12" required>${values}</textarea><p class="setup-status ${state.error?"is-error":""}" aria-live="polite">${state.error||`${state.values?.length||DEFAULTS.length} values ready.`}</p><button class="primary setup-start" type="submit">Start the game</button></form></section></main>`}
function caseView(c){const mine=c.number===state.mine,active=state.phase==="choose"||(state.phase==="opening"&&!mine),label=c.opened?peso(c.value):mine?`#${c.number} · YOURS`:`#${c.number}`;return `<button class="case ${c.opened?"is-open":""} ${mine?"is-mine":""}" data-case="${c.number}" ${!active||c.opened?"disabled":""} aria-label="${c.opened?`Briefcase ${c.number}, opened, ${peso(c.value)}`:mine?`Your briefcase, number ${c.number}`:`Briefcase ${c.number}`}"><i aria-hidden="true"></i><span>${label}</span></button>`}
function board(){const opened=new Map(),seen=new Map();state.cases.filter(c=>c.opened).forEach(c=>opened.set(c.value,(opened.get(c.value)||0)+1));return [...state.values].sort((a,b)=>a-b).map(v=>{const occurrence=(seen.get(v)||0)+1;seen.set(v,occurrence);return `<li class="${occurrence<=(opened.get(v)||0)?"eliminated":""}">${peso(v)}</li>`}).join("")}
function controls(){if(state.phase==="offer")return `<section class="offer"><p>Banker’s offer</p><h2>${peso(state.offer)}</h2><div><button class="primary" data-action="deal">Deal</button><button class="secondary" data-action="nodeal">No Deal</button></div></section>`;if(state.phase==="finished"){const own=state.cases.find(c=>c.number===state.mine);return `<section class="offer"><p>Your result</p><h2>${peso(state.result)}</h2><small>Your Briefcase #${own.number} held ${peso(own.value)}.</small><button class="primary full" data-action="restart">Play again</button></section>`}const n=state.phase==="opening"?Math.max(0,state.roundTarget-state.opened):1;return `<section class="round-card"><p>${state.phase==="choose"?"Choose one case to keep":`Open ${n} more ${n===1?"case":"cases"}`}</p><strong>${state.phase==="choose"?"Your luck starts here.":"Every reveal changes the offer."}</strong></section>`}
function gameView(){const label=state.phase==="choose"?"Opening move":state.phase==="finished"?"Game complete":`Round ${state.round+1}`;return `<main id="main"><header class="masthead"><a class="logo" href="#" data-action="setup"><small>KAPAMILYA</small><span>DEAL</span><i>or</i><span>NO DEAL</span></a><div class="round-status"><span>${label}</span><b>${remaining().length} values remain</b></div><button class="restart" data-action="setup">Game setup</button></header><div class="game-shell"><aside class="money-board"><h2>Prize board</h2><ol>${board()}</ol></aside><section class="stage"><div class="stage-heading"><p>${label}</p><h1>Deal or<br><em>No Deal?</em></h1></div><div class="cases" style="--case-columns:${Math.min(6,Math.max(2,Math.ceil(Math.sqrt(state.caseCount))))}">${state.cases.map(caseView).join("")}</div></section><aside class="control-room"><div class="host-message" aria-live="polite"><span>Host</span><p>${state.message}</p></div>${controls()}<section class="game-rules"><h2>How this game opens</h2><p>Three cases early, two as the board narrows, then one case at a time near the end.</p></section></aside></div></main>`}
function render(){app.innerHTML=state.phase==="setup"?setupView():gameView();document.querySelector("#setup-form")?.addEventListener("submit",setup);document.querySelectorAll("[data-case]").forEach(b=>b.onclick=()=>state.phase==="choose"?choose(+b.dataset.case):openCase(+b.dataset.case));document.querySelectorAll('[data-action="setup"]').forEach(b=>b.onclick=e=>{e.preventDefault();showSetup()});document.querySelector('[data-action="deal"]')?.addEventListener("click",deal);document.querySelector('[data-action="nodeal"]')?.addEventListener("click",noDeal);document.querySelector('[data-action="restart"]')?.addEventListener("click",()=>start(state.caseCount,state.values))}
render();
